version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Allow both direct and indirect dependency updates
    open-pull-requests-limit: 10
    # Ignore major version updates (only allow minor and patch)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group updates by type
    groups:
      production-dependencies:
        patterns:
          - "react*"
          - "electron*"
          - "better-sqlite3"
          - "chart.js"
          - "electron-is-dev"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"
          - "react-scripts"
          - "electron-builder"
          - "electron-rebuild"
          - "concurrently"
          - "wait-on"
        update-types:
          - "minor"
          - "patch"
    # Security updates get their own PRs
    assignees:
      - "appatalks"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "appatalks"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "automated"
